version: "3"
services:
  frontend_service:
    image: "app"
    build: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend_service
  backend_service:
    image: "api"
    build: Api.Dockerfile
    ports:
      - "3030:3030"